# Generated by Django 4.2.2 on 2023-06-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jogador_game_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='game_pass',
            field=models.CharField(default='e0v2rbsS', max_length=8),
        ),
    ]
