# Generated by Django 4.2.2 on 2023-06-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_jogador_game_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='log',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='game_pass',
            field=models.CharField(default='FBTNS0si', max_length=8),
        ),
    ]
