# Generated by Django 4.2.2 on 2023-06-07 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareType',
            fields=[
                ('type_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_name', models.CharField(max_length=25)),
                ('soft_version', models.IntegerField()),
                ('soft_size', models.IntegerField()),
                ('soft_ram', models.IntegerField()),
                ('soft_hidden', models.BooleanField()),
                ('soft_hidden_with', models.BigIntegerField()),
                ('type_of_software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software.softwaretype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
