# Generated by Django 4.2.2 on 2023-06-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='soft_hidden',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='software',
            name='soft_hidden_with',
            field=models.BigIntegerField(default=0),
        ),
    ]
