# Generated by Django 4.2.2 on 2023-06-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_alter_software_soft_hidden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='soft_name',
            field=models.CharField(default='soft', max_length=25),
        ),
    ]
